(cl:in-package nav_sensors-msg)
(cl:export '(PACKET_COUNT-VAL
          PACKET_COUNT
          PACKET_ID-VAL
          PACKET_ID
          VERSION-VAL
          VERSION
          SYSTEM_TYPE-VAL
          SYSTEM_TYPE
          SYSTEM_SUBTYPE-VAL
          SYSTEM_SUBTYPE
          FW_MAJOR_VERSION-VAL
          FW_MAJOR_VERSION
          FW_MINOR_VERSION-VAL
          FW_MINOR_VERSION
          FW_PATCH_VERSION-VAL
          FW_PATCH_VERSION
          FW_BUILD_VERSION-VAL
          FW_BUILD_VERSION
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MINUTE-VAL
          MINUTE
          SECOND-VAL
          SECOND
          COORDINATE_SYSTEM-VAL
          COORDINATE_SYSTEM
))