
uint16 packet_count # number of packets
uint8 packet_id
uint8 version #
uint8 system_type # System Type (should be = 76 = 0x4c for Wayfinder DVL)
uint8 system_subtype # Variant on the system type e.g frequency or transducer type
uint8 fw_major_version
uint8 fw_minor_version
uint8 fw_patch_version
uint8 fw_build_version
uint8 year
uint8 month
uint8 day
uint8 hour
uint8 minute
uint8 second
uint8 coordinate_system